services:
  simple-blob-pgsql:
    image: postgis/postgis
    container_name: simple-blob-pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - simple-blob-network
    volumes:
      # ensure you have created the var/db/pgsql folder in the host
      # https://hub.docker.com/r/postgis/postgis
      - /var/db/pgsql:/var/lib/postgresql/data

  simple-blob-api:
    image: vedph2020/simple-blob-api:2.0.4
    ports:
        # https://stackoverflow.com/questions/48669548/why-does-aspnet-core-start-on-port-80-from-within-docker
        - 2418:80
    depends_on:
        - simple-blob-pgsql
    environment:
        # for Windows use : as separator, for non Windows use __
        # (see https://github.com/aspnet/Configuration/issues/469)
        - CONNECTIONSTRINGS__DEFAULT=User ID=postgres;Password=postgres;Host=simple-blob-pgsql;Port=5432;Database={0};
        # - ALLOWED__ORIGINS__3=http://www.something.com
        - SEEDDELAY=30
        - STOCKUSERS__0__PASSWORD=P4ss-W0rd!
        - MESSAGING__APIROOTURL=https://simpleblob.azurewebsites.net/api/
        - MESSAGING__APPROOTURL=https://fusisoft.it/apps/blob/
        - MESSAGING__SUPPORTEMAIL=webmaster@fusisoft.net

    networks:
        - simple-blob-network

networks:
  simple-blob-network:
    driver: bridge
